# Responsibility: Pydantic schemas for session request/response validation

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class SessionCreate(BaseModel):
    """Payload sent by the frontend when starting a new session."""

    model_config = ConfigDict(populate_by_name=True)

    mode: Literal["interview", "social"] = Field(
        ...,
        description="Training mode — interview or social",
    )
    job_title: str | None = Field(
        default=None,
        alias="jobTitle",
        max_length=150,
        description="Target job title — required for interview mode",
    )
    scenario: str | None = Field(
        default=None,
        max_length=150,
        description="Social scenario — required for social mode",
    )
    duration_s: int | None = Field(
        default=None,
        alias="durationS",
        ge=10,
        le=300,
        description="Intended session duration in seconds",
    )
    difficulty: str | None = Field(
        default="balanced",
        description="Difficulty level: easy, balanced, or hard",
    )
    questions: list[str] | None = Field(
        default=None,
        description="Questions generated by Gemini for this session",
    )


class SessionResponse(BaseModel):
    """Response returned after creating a session."""

    session_id: str
    job_id: str
    status: str = "processing"


class JobStatusResponse(BaseModel):
    """Response returned when polling job status."""

    job_id: str
    status: Literal["pending_upload", "processing", "complete", "error"]
    session_id: str | None = None
    error: str | None = None
